# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="agnoster"

plugins=(git)

source $ZSH/oh-my-zsh.sh

alias l="ls -la"
alias c="clear"
alias e="exit"
alias v="vim"
alias p="python3"
alias k="kubectl"
alias kk="bash ~/scripts/config_kube.sh"
alias t="tree"
alias w="bash ~/scripts/switchwallpaper.sh"
alias t="python3 ./scripts/config_terminator.py"
alias bat="batcat"

export ZSH_COMPDUMP=$ZSH/cache/.zcompdump-$HOST
export TERM=xterm-256color

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/bin/terraform terraform

eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv zsh)"
source ~/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
