" ============================================================================
"                                  ~/.vimrc
" ============================================================================

" ----------------------------------------------------------------------------
" 1) BASIC SETTINGS
" ----------------------------------------------------------------------------

" Disable specific languages from vim-polyglot
let g:polyglot_disabled = ['markdown', 'csv']

set nocompatible
filetype plugin indent on
syntax on

set autoindent
set diffopt+=vertical
set encoding=utf-8
set hidden
set mouse=a
set noswapfile
set numberwidth=4
set number
set relativenumber
set scrolloff=10
set shiftwidth=4
set sidescrolloff=10
set smartindent
set smartcase
set softtabstop=4
set tabstop=4

if has('persistent_undo')
  set undofile
  set undodir=~/.vim/undo
endif

" Search highlight
set hlsearch
set incsearch

" Store viminfo in a custom location
set viminfo='100,n$HOME/.vim/files/info/viminfo

" Leader key = Space
nnoremap <SPACE> <Nop>
let mapleader=" "
let maplocalleader=" "

" Load config
source ~/.vim/config/mapping.vim
source ~/.vim/config/coc.vim
source ~/.vim/config/nerdtree.vim
source ~/.vim/config/general.vim
source ~/.vim/config/autocmd.vim

" ----------------------------------------------------------------------------
" 2) PLUGINS (vim-plug)
" ----------------------------------------------------------------------------
call plug#begin()

" Start screen
Plug 'mhinz/vim-startify'

" Agent IA
Plug 'Exafunction/codeium.vim'

" Completion / LSP
Plug 'neoclide/coc.nvim', {'branch': 'release'}

" File tree
Plug 'preservim/nerdtree'
Plug 'tiagofumo/vim-nerdtree-syntax-highlight'
Plug 'ryanoasis/vim-devicons'

" Fuzzy finder
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'

" Theme + statusline
Plug 'sainnhe/vim-color-forest-night'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

" Parentheses rainbow
Plug 'kien/rainbow_parentheses.vim'

" Editing / syntax helpers
Plug 'tpope/vim-surround'
Plug 'sheerun/vim-polyglot'
Plug 'vim-syntastic/syntastic'

" CSV syntaxys
Plug 'chrisbra/csv.vim'

" 42 header
Plug 'pbondoer/vim-42header'

" Git
Plug 'tpope/vim-fugitive'
Plug 'zivyangll/git-blame.vim'

" Extra colorschemes
Plug 'flazz/vim-colorschemes'

" Buffer manager
Plug 'moll/vim-bbye'

call plug#end()

" ----------------------------------------------------------------------------
" 3) STARTIFY CONFIG
" ----------------------------------------------------------------------------
let g:startify_bookmarks = [
      \ { 'z' : '~/.zshrc' },
      \ { 'v' : '~/.vimrc' },
      \ { 'c' : '~/.config' },
      \ { 's' : '~/scripts' },
      \ { 'd' : '~/Documents'},
      \ { 'n' : '~/.config/nvim/init.lua'},
      \ { 'i' : '~/.config/i3/config' },
      \ { 't' : '~/.config/terminator/config' },
      \ { 'C' : '~/.vim/plugin/cheatsheet.vim' },
      \ { 'm' : '~/.vim/config' },
      \ ]

let g:startify_lists = [
      \ { 'header': ['  Bookmarks'],                        'type': 'bookmarks' },
      \ { 'header': ['  Current Recent Use ' . getcwd()],   'type': 'dir' },
      \ { 'header': ['  Recent Use'],                       'type': 'files' },
      \ ]

nnoremap <leader>st :Startify<CR>

" ----------------------------------------------------------------------------
" 4) THEME CONFIG (Everforest)
" ----------------------------------------------------------------------------
if has('termguicolors')
  set termguicolors
endif

set background=dark

" Everforest settings
let g:everforest_background = 'medium'
let g:everforest_better_performance = 1
let g:everforest_transparent_background = 1

colorscheme everforest

" ----------------------------------------------------------------------------
" 5) AIRLINE
" ----------------------------------------------------------------------------
set ttimeoutlen=50
let g:airline_theme = 'everforest'
let g:airline#extensions#branch#enabled = 1

" Show only the filename, not the full path
let g:airline#parts#ffenc#skip_expected_string='utf-8[unix]'
set noshowmode

" Filename only
let g:airline_section_c = '%t'

" Remove file encoding / fileformat
let g:airline_section_y = ''

" Remove filetype (json)
let g:airline_section_x = ''

let g:airline_section_c = '%t%m'

" Optional: remove the warning/error section that may show "{...} ON"
let g:airline_section_warning = ''
let g:airline#extensions#tabline#enabled = 1

" ----------------------------------------------------------------------------
" 6) RAINBOW PARENTHESES
" ----------------------------------------------------------------------------
let g:rbpt_colorpairs = [
      \ ['brown',       'RoyalBlue3'],
      \ ['Darkblue',    'SeaGreen3'],
      \ ['darkgray',    'DarkOrchid3'],
      \ ['darkgreen',   'firebrick3'],
      \ ['darkcyan',    'RoyalBlue3'],
      \ ['darkred',     'SeaGreen3'],
      \ ['darkmagenta', 'DarkOrchid3'],
      \ ['brown',       'firebrick3'],
      \ ['gray',        'RoyalBlue3'],
      \ ['black',       'SeaGreen3'],
      \ ['darkmagenta', 'DarkOrchid3'],
      \ ['Darkblue',    'firebrick3'],
      \ ['darkgreen',   'RoyalBlue3'],
      \ ['darkcyan',    'SeaGreen3'],
      \ ['darkred',     'DarkOrchid3'],
      \ ['red',         'firebrick3'],
      \ ]
let g:rbpt_max = 16
let g:rbpt_loadcmd_toggle = 0

nnoremap <leader>po :RainbowParenthesesToggle<CR>

" Always on
au VimEnter * RainbowParenthesesToggle
au Syntax * RainbowParenthesesLoadRound
au Syntax * RainbowParenthesesLoadSquare
au Syntax * RainbowParenthesesLoadBraces

" ----------------------------------------------------------------------------
" 7) 42 HEADER USER INFO
" ----------------------------------------------------------------------------
let g:user42 = 'mjulliat'
let g:mail42 = 'mjulliat@student.42.ch'

" ----------------------------------------------------------------------------
" 8) FZF
" ----------------------------------------------------------------------------

" Auto clean the highlight buffer
augroup fzf
autocmd!
autocmd BufEnter,BufWinEnter * if &buftype == '' | let @/ = '' | endif
augroup END

nnoremap <leader>ff :FZF<CR>
nnoremap <leader>rg :Rg<CR>
let g:fzf_layout = { 'down': '50%' }
let g:fzf_preview_window = ['right:60%']

" Use ripgrep for :Rg
command! -bang -nargs=* Rg
  \ call fzf#vim#grep(
  \   'rg --column --line-number --no-heading --color=always --smart-case '.shellescape('\b'.<q-args>),
  \   1,
  \   fzf#vim#with_preview(),
  \   <bang>0)

" Search word under cursor
nnoremap <leader>rw :Rg <C-R><C-W><CR>

" ----------------------------------------------------------------------------
" 9) GIT (FUGITIVE)
" ----------------------------------------------------------------------------

nnoremap <leader>ga :Git add .<CR>
nnoremap <Leader>gb :<C-u>call gitblame#echo()<CR>

" ----------------------------------------------------------------------------
" 10) CODEIUM
" ----------------------------------------------------------------------------

let g:codeium_disable_bindings = 1

inoremap <silent><script><expr> <C-J> codeium#Accept()
nnoremap <leader>ce :CodeiumEnable<CR>
nnoremap <leader>cd :CodeiumDisable<CR>
